server:
  port: 47170
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/event-system
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        highlight_sql: false
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration
  data:
    redis:
      cluster:
        connect-ip: localhost
        nodes: localhost:7001, localhost:7002, localhost:7003
        max-redirects: 3
      username: root
      password: root
      timeout: 5000
      client-type: lettuce
      streams:
        consumers:
          - streamKey: EVENT_STREAM
            groupName: EVENT_GROUP
            consumerPrefix: EVENT_CONSUMER
            consumerCount: 2